server:
  port: 8082

spring:
  application:
    name: notification
  datasource:
    username: emmydev
    url: jdbc:postgresql://postgres:5432/notification
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: emmyshoppinghub@gmail.com
    password: rvyniuyxsmzwanvw
    properties:
      smtp:
        auth: true
        starttls:
          enable: true
  zipkin:
    base-url: http://zipkin:9411
  rabbitmq:
    addresses: rabbitmq:5672

eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver:8761/eureka
    fetch-registry: true
    register-with-eureka: true

rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    notification: notification.queue
  routing-keys:
    internal-notification: internal.notification.routing-key